"use strict";
const mongoose = require("../../config/database").mongoose,
  Schema = mongoose.Schema,
  modelName = "RealEstateRecord";

const realEstateSchema = new Schema(
  {
    SystemSourceLink: {
      type: String,
      index: true,
      unique: true
    }
  },
  {
    strict: false,
    versionKey: false,
    autoIndex: true,
    timestamps: {
      createdAt: "CreatedAt",
      updatedAt: "UpdatedAt"
    }
  }
);

//Query normal list index
realEstateSchema.index({
  AreaCountryName: 1,
  AreaDistrictName: 1,
  AreaProvinceName: 1,
  AreaStateName: 1,
  AreaWardName: 1,
  AreaTypeName: 1,
  SystemPostType: 1,
  CreatedAt: -1,
  UpdatedAt: -1,
  ActivatedAt: -1,
}); // schema level

//Index for search contact
realEstateSchema.index({
  ContactAddress: 1,
  ContactEmail: 1,
  ContactPhone: 1,
}); // schema level

// realEstateSchema.index({
//   AreaCountryName: 1,
//   AreaDistrictName: 1,
//   AreaProvinceName: 1,
//   AreaStateName: 1,
//   AreaWardName: 1,
//   AreaTypeName: 1,
//   CommentsContent: 1,
//   CommentsDate: 1,
//   CommentsID: 1,
//   CommentsOwner: 1,
//   CommentsRelated: 1,
//   ContactAddress: 1,
//   ContactAge: 1,
//   ContactCompany: 1,
//   ContactDob: 1,
//   ContactDomain: 1,
//   ContactEmail: 1,
//   ContactGender: 1,
//   ContactIdentity: 1,
//   ContactJob: 1,
//   ContactName: 1,
//   ContactPhone: 1,
//   ContactPosition: 1,
//   ContactTypeName: 1,
//   HouseAbilites: 1,
//   HouseBackYard: 1,
//   HouseBasement: 1,
//   HouseBedRooms: 1,
//   HouseCompleteName: 1,
//   HouseConstructionHeight: 1,
//   HouseConstructionSquare: 1,
//   HouseElectricity: 1,
//   HouseFloors: 1,
//   HouseFloorsSquare: 1,
//   HouseFloorsType: 1,
//   HouseFrontYard: 1,
//   HouseFurnitureList: 1,
//   HouseFurnitureName: 1,
//   HouseGarage: 1,
//   HouseKitchens: 1,
//   HouseLivingRooms: 1,
//   HouseMiddleFloors: 1,
//   HouseNearbyPlace: 1,
//   HousePool: 1,
//   HouseQualityName: 1,
//   HouseRoofType: 1,
//   HouseStairType: 1,
//   HouseTerrace: 1,
//   HouseToilets: 1,
//   HouseWallType: 1,
//   HouseWater: 1,
//   ImagesDroneNearby: 1,
//   ImagesDroneOutSide: 1,
//   ImagesHouse: 1,
//   ImagesInside: 1,
//   ImagesJuridical: 1,
//   ImagesNearBy: 1,
//   ImagesPlanRoadSquare: 1,
//   ImagesPlanUsage: 1,
//   ImagesV360Inside: 1,
//   ImagesV360Outside: 1,
//   JuridicalConstructionSquare: 1,
//   JuridicalContructionLimitation: 1,
//   JuridicalFloorSquare: 1,
//   JuridicalLandCode: 1,
//   JuridicalLandSquare: 1,
//   JuridicalLatest: 1,
//   JuridicalMainConstruction: 1,
//   JuridicalName: 1,
//   JuridicalOtherObject: 1,
//   JuridicalPaperCode: 1,
//   JuridicalStatusName: 1,
//   JuridicalSubConstructions: 1,
//   JuridicalUpdates: 1,
//   JuridicalUsingStatusName: 1,
//   LandAgricultureSquare: 1,
//   LandDefaultSquare: 1,
//   LandDirectionName: 1,
//   LandFrontSides: 1,
//   LandFrontWidth: 1,
//   LandLong: 1,
//   LandPlanningTypeName: 1,
//   LandRealConstructionSquare: 1,
//   LandRealitySquare: 1,
//   LandRoadSquare: 1,
//   LandShapeName: 1,
//   LandWidth: 1,
//   LocationDistanceToCityCenter: 1,
//   LocationFrontStreetWidth: 1,
//   LocationFullAddress: 1,
//   LocationHomeNumber: 1,
//   LocationMapLat: 1,
//   LocationMapLong: 1,
//   LocationPositionName: 1,
//   LocationProjectName: 1,
//   LocationStreetName: 1,
//   LocationStreetWidth: 1,
//   LocationTunel: 1,
//   NegativeInfo: 1,
//   OthersInfo: 1,
//   Plan1ySalePrice: 1,
//   Plan3mSalePrice: 1,
//   Plan5ySalePrice: 1,
//   Plan6mSalePrice: 1,
//   PlanEvaluation: 1,
//   PlanInvestmentPoints: 1,
//   PlanInvestmentRankingName: 1,
//   PlanInvestmentTypeName: 1,
//   PlanLoanMaximum: 1,
//   PlanLoanPayRateMonthly: 1,
//   PlanLoanPercentage: 1,
//   PlanLoanTime: 1,
//   PlanProfitPercentage: 1,
//   PlanRentPrice: 1,
//   PlanRentUnitPrice: 1,
//   PositiveInfo: 1,
//   SystemAnalysisLevel: 1,
//   SystemCollectionPoints: 1,
//   SystemCreatorName: 1,
//   SystemDateOfPost: 1,
//   SystemInfoConfirmStatusName: 1,
//   SystemInfoSecurityLevelName: 1,
//   SystemInfoUsingStatusName: 1,
//   SystemInfoVisibleStatus: 1,
//   SystemInfomationRankingName: 1,
//   SystemLastActiveDate: 1,
//   SystemModifierName: 1,
//   SystemNote: 1,
//   SystemPostType: 1,
//   SystemPostUrl: 1,
//   SystemRecordContent: 1,
//   SystemRecordTitle: 1,
//   SystemRecordType: 1,
//   SystemSourceLink: 1,
//   SystemSourceName: 1,
//   SystemSourceType: 1,
//   SystemViewCount: 1,
//   SystemViewerName: 1,
//   ValueDiscussPrice: 1,
//   ValueHousePrice: 1,
//   ValueHouseUnitPrice: 1,
//   ValueLandPrice: 1,
//   ValueLandUnitPrice: 1,
//   ValueRentPrice: 1,
//   ValueRentUnitPrice: 1,
//   ValueSalePrice: 1,
//   ValueSaleUnitPrice: 1,
//   CreatedAt: 1,
//   UpdatedAt: 1,
//   // ViewCount: 1,
//   // ClickCount: 1,
//   // ShareCount: 1,
//   // InvestmentRating: 1,
//   // DataRating: 1,
//   ActivatedAt: 1,
// }); // schema level

const model = mongoose.model(modelName, realEstateSchema);
module.exports = {
  modelData: model,
  modelName: modelName
};
